import { createBuiltinCommand } from "../lib/commandTemplate";
import type { CommandTemplate } from "../types";

const u = ["universal"] as const;
const deb = ["debian"] as const;
const rhel = ["rhel"] as const;
const alpine = ["alpine"] as const;
const suse = ["suse"] as const;
const arch = ["arch"] as const;

const PKG_PATTERN = {
  label: "搜什么软件",
  inputKind: "search-keyword" as const,
  keywordVariant: "package" as const,
};

const FILE_GREP_PATTERN = {
  label: "要找什么内容",
  inputKind: "search-keyword" as const,
  keywordVariant: "file-content" as const,
};

const FILE_NAME_PATTERN = {
  label: "文件名包含",
  inputKind: "search-keyword" as const,
  keywordVariant: "filename" as const,
};

export const BUILTIN_COMMANDS: CommandTemplate[] = [
  // service
  createBuiltinCommand({
    id: "svc-status",
    title: "查看服务状态",
    description: "systemctl status，查看单元状态与最近日志摘要",
    subcategory: "service",
    distroFamilies: [...u],
    template: "systemctl status {service}",
    paramOverrides: { service: { placeholder: "nginx" } },
  }),
  createBuiltinCommand({
    id: "svc-start",
    title: "启动服务",
    subcategory: "service",
    distroFamilies: [...u],
    template: "sudo systemctl start {service}",
  }),
  createBuiltinCommand({
    id: "svc-stop",
    title: "停止服务",
    subcategory: "service",
    distroFamilies: [...u],
    template: "sudo systemctl stop {service}",
  }),
  createBuiltinCommand({
    id: "svc-restart",
    title: "重启服务",
    subcategory: "service",
    distroFamilies: [...u],
    template: "sudo systemctl restart {service}",
  }),
  createBuiltinCommand({
    id: "svc-enable",
    title: "开机自启",
    subcategory: "service",
    distroFamilies: [...u],
    template: "sudo systemctl enable {service}",
  }),
  createBuiltinCommand({
    id: "svc-disable",
    title: "禁用开机自启",
    subcategory: "service",
    distroFamilies: [...u],
    template: "sudo systemctl disable {service}",
  }),
  createBuiltinCommand({
    id: "svc-failed",
    title: "列出失败单元",
    subcategory: "service",
    distroFamilies: [...u],
    template: "systemctl --failed",
    params: [],
  }),
  createBuiltinCommand({
    id: "svc-reload",
    title: "重载 systemd",
    subcategory: "service",
    distroFamilies: [...u],
    template: "sudo systemctl daemon-reload",
    params: [],
  }),
  createBuiltinCommand({
    id: "svc-cat",
    title: "查看 unit 文件",
    subcategory: "service",
    distroFamilies: [...u],
    template: "systemctl cat {service}",
  }),

  // journal
  createBuiltinCommand({
    id: "jnl-follow",
    title: "跟踪服务日志",
    description: "journalctl 实时跟踪，需 sudo 时自行加 sudo",
    subcategory: "journal",
    distroFamilies: [...u],
    template: "journalctl -u {service} -f --no-pager -n {lines}",
    paramOverrides: { lines: { default: "200", label: "初始行数" } },
  }),
  createBuiltinCommand({
    id: "jnl-range",
    title: "按时间查日志",
    subcategory: "journal",
    distroFamilies: [...u],
    template:
      'journalctl -u {service} --since "{since}" --until "{until}" --no-pager',
    paramOverrides: {
      since: { default: "1 hour ago", placeholder: "1 hour ago" },
      until: { default: "now", required: false },
    },
  }),
  createBuiltinCommand({
    id: "jnl-boot-err",
    title: "本次启动错误日志",
    subcategory: "journal",
    distroFamilies: [...u],
    template: "journalctl -b -p err..alert --no-pager",
    params: [],
  }),
  createBuiltinCommand({
    id: "jnl-disk",
    title: "日志磁盘占用",
    subcategory: "journal",
    distroFamilies: [...u],
    template: "journalctl --disk-usage",
    params: [],
  }),
  createBuiltinCommand({
    id: "jnl-today-err",
    title: "今日错误日志",
    subcategory: "journal",
    distroFamilies: [...u],
    template: "journalctl -p err..alert --since today --no-pager",
    params: [],
  }),
  createBuiltinCommand({
    id: "jnl-vacuum",
    title: "清理 journal 体积",
    description: "将 journal 压缩到指定大小以下",
    subcategory: "journal",
    distroFamilies: [...u],
    template: "sudo journalctl --vacuum-size={size}",
    paramOverrides: { size: { default: "500M", label: "保留上限" } },
  }),

  // disk
  createBuiltinCommand({
    id: "disk-df",
    title: "磁盘空间概览",
    subcategory: "disk",
    distroFamilies: [...u],
    template: "df -hT",
    params: [],
  }),
  createBuiltinCommand({
    id: "disk-du",
    title: "目录占用",
    subcategory: "disk",
    distroFamilies: [...u],
    template: "du -sh {path}",
    paramOverrides: { path: { placeholder: "/var/log" } },
  }),
  createBuiltinCommand({
    id: "disk-du-depth",
    title: "目录分层占用",
    subcategory: "disk",
    distroFamilies: [...u],
    template: "du -h --max-depth={depth} {path}",
    paramOverrides: {
      depth: { default: "1", label: "深度" },
      path: { placeholder: "." },
    },
  }),
  createBuiltinCommand({
    id: "disk-large",
    title: "查找大文件",
    subcategory: "disk",
    distroFamilies: [...u],
    template:
      "find {path} -type f -size +{size} -printf '%s %p\\n' 2>/dev/null | sort -nr | head -n {count}",
    paramOverrides: {
      path: { placeholder: "/" },
      size: { default: "100M", label: "大于" },
      count: { default: "20", label: "显示条数" },
    },
  }),
  createBuiltinCommand({
    id: "disk-lsblk",
    title: "块设备与挂载",
    subcategory: "disk",
    distroFamilies: [...u],
    template: "lsblk -f",
    params: [],
  }),
  createBuiltinCommand({
    id: "disk-df-i",
    title: "inode 使用",
    description: "inode 用尽时 df -h 仍显示有空间",
    subcategory: "disk",
    distroFamilies: [...u],
    template: "df -hi",
    params: [],
  }),
  createBuiltinCommand({
    id: "disk-findmnt",
    title: "挂载点一览",
    subcategory: "disk",
    distroFamilies: [...u],
    template: "findmnt -avo TARGET,SOURCE,FSTYPE,SIZE,USED,AVAIL",
    params: [],
  }),

  // process
  createBuiltinCommand({
    id: "proc-pgrep",
    title: "按名查进程",
    description: "等同 ps -ef | grep，列出含该关键词的进程行",
    subcategory: "process",
    distroFamilies: [...u],
    template: "ps -ef | grep '{pattern}' | grep -v grep",
    paramOverrides: {
      pattern: {
        label: "进程名",
        placeholder: "nginx、python、sshd…",
        inputKind: "process-name",
      },
    },
  }),
  createBuiltinCommand({
    id: "proc-kill",
    title: "结束进程",
    description: "默认 SIGTERM(15)；强制结束可填 9",
    subcategory: "process",
    distroFamilies: [...u],
    template: "kill -{signal} {pid}",
    paramOverrides: { signal: { default: "15", required: false } },
  }),
  createBuiltinCommand({
    id: "proc-top",
    title: "资源快照",
    subcategory: "process",
    distroFamilies: [...u],
    template: "top -b -n 1 | head -n {lines}",
    paramOverrides: { lines: { default: "20" } },
  }),
  createBuiltinCommand({
    id: "proc-ps-mem",
    title: "内存占用 Top",
    subcategory: "process",
    distroFamilies: [...u],
    template: "ps aux --sort=-%mem | head -n {lines}",
    paramOverrides: { lines: { default: "15", label: "行数" } },
  }),
  createBuiltinCommand({
    id: "proc-pstree",
    title: "进程树",
    subcategory: "process",
    distroFamilies: [...u],
    template: "pstree -p",
    params: [],
  }),
  createBuiltinCommand({
    id: "proc-lsof-port",
    title: "端口占用详情",
    subcategory: "network",
    distroFamilies: [...u],
    template: "sudo lsof -i :{port}",
  }),
  createBuiltinCommand({
    id: "proc-lsof-pid",
    title: "进程打开的文件",
    subcategory: "process",
    distroFamilies: [...u],
    template: "sudo lsof -p {pid}",
  }),
  createBuiltinCommand({
    id: "proc-iostat",
    title: "磁盘 IO 采样",
    description: "需安装 sysstat 包",
    subcategory: "process",
    distroFamilies: [...u],
    template: "iostat -x 1 {count}",
    paramOverrides: { count: { default: "3", label: "采样次数" } },
  }),
  createBuiltinCommand({
    id: "proc-vmstat",
    title: "系统资源采样",
    subcategory: "process",
    distroFamilies: [...u],
    template: "vmstat 1 {count}",
    paramOverrides: { count: { default: "5", label: "采样次数" } },
  }),

  // network
  createBuiltinCommand({
    id: "net-ss",
    title: "监听端口",
    description: "留空列出全部 TCP/UDP 监听；填写端口则查占用进程",
    subcategory: "network",
    distroFamilies: [...u],
    template: "ss -tulnp",
    params: [
      {
        name: "port",
        label: "端口（可选）",
        required: false,
        inputKind: "port",
      },
    ],
  }),
  createBuiltinCommand({
    id: "net-ip",
    title: "网卡与地址",
    subcategory: "network",
    distroFamilies: [...u],
    template: "ip -br a",
    params: [],
  }),
  createBuiltinCommand({
    id: "net-route",
    title: "路由表",
    subcategory: "network",
    distroFamilies: [...u],
    template: "ip route",
    params: [],
  }),
  createBuiltinCommand({
    id: "net-ping",
    title: "Ping 测试",
    subcategory: "network",
    distroFamilies: [...u],
    template: "ping -c {count} {host}",
    paramOverrides: { count: { default: "4", label: "次数" } },
  }),
  createBuiltinCommand({
    id: "net-dig",
    title: "DNS 查询",
    subcategory: "network",
    distroFamilies: [...u],
    template: "dig {host}",
  }),
  createBuiltinCommand({
    id: "net-curl",
    title: "HTTP 探测",
    description: "检查 URL 是否可达及状态码",
    subcategory: "network",
    distroFamilies: [...u],
    template:
      "curl -o /dev/null -s -w 'HTTP %{http_code} time %{time_total}s\\n' '{url}'",
    params: [
      {
        name: "url",
        label: "URL",
        placeholder: "http://127.0.0.1:8080/health",
      },
    ],
  }),
  createBuiltinCommand({
    id: "net-ss-summary",
    title: "连接统计摘要",
    subcategory: "network",
    distroFamilies: [...u],
    template: "ss -s",
    params: [],
  }),
  createBuiltinCommand({
    id: "net-ss-estab",
    title: "已建立连接",
    subcategory: "network",
    distroFamilies: [...u],
    template: "ss -tan state established | head -n {count}",
    paramOverrides: { count: { default: "30", label: "行数" } },
  }),
  createBuiltinCommand({
    id: "net-traceroute",
    title: "路由跟踪",
    subcategory: "network",
    distroFamilies: [...u],
    template: "traceroute -n {host}",
    paramOverrides: { host: { placeholder: "8.8.8.8" } },
  }),
  createBuiltinCommand({
    id: "net-ufw",
    title: "UFW 防火墙状态",
    description: "查看 Ubuntu/Debian 上 UFW 是否启用及规则",
    subcategory: "network",
    distroFamilies: [...deb],
    template: "sudo ufw status verbose",
    params: [],
  }),
  createBuiltinCommand({
    id: "net-ufw-allow",
    title: "UFW 开放端口",
    description: "允许 TCP 端口入站连接",
    subcategory: "network",
    distroFamilies: [...deb],
    template: "sudo ufw allow {port}/tcp",
  }),
  createBuiltinCommand({
    id: "net-ufw-deny",
    title: "UFW 拒绝端口",
    description: "拒绝 TCP 端口入站连接",
    subcategory: "network",
    distroFamilies: [...deb],
    template: "sudo ufw deny {port}/tcp",
  }),
  createBuiltinCommand({
    id: "net-firewalld",
    title: "firewalld 规则概览",
    description: "查看 RHEL/CentOS 等系统的 firewalld 配置",
    subcategory: "network",
    distroFamilies: [...rhel],
    template: "sudo firewall-cmd --list-all",
    params: [],
  }),
  createBuiltinCommand({
    id: "net-firewalld-ports",
    title: "firewalld 已开放端口",
    subcategory: "network",
    distroFamilies: [...rhel],
    template: "sudo firewall-cmd --list-ports",
    params: [],
  }),
  createBuiltinCommand({
    id: "net-firewalld-allow",
    title: "firewalld 开放端口",
    description: "永久开放 TCP 端口并立即生效",
    subcategory: "network",
    distroFamilies: [...rhel],
    template:
      "sudo firewall-cmd --permanent --add-port={port}/tcp && sudo firewall-cmd --reload",
  }),
  createBuiltinCommand({
    id: "net-firewalld-remove",
    title: "firewalld 关闭端口",
    description: "永久移除 TCP 端口放行并立即生效",
    subcategory: "network",
    distroFamilies: [...rhel],
    template:
      "sudo firewall-cmd --permanent --remove-port={port}/tcp && sudo firewall-cmd --reload",
  }),
  createBuiltinCommand({
    id: "net-iptables",
    title: "iptables 规则",
    description: "查看 iptables 过滤规则（通用）",
    subcategory: "network",
    distroFamilies: [...u],
    template: "sudo iptables -L -n -v",
    params: [],
  }),
  createBuiltinCommand({
    id: "net-nft",
    title: "nftables 规则",
    description: "查看 nftables 规则集",
    subcategory: "network",
    distroFamilies: [...u],
    template: "sudo nft list ruleset",
    params: [],
  }),

  // package debian
  createBuiltinCommand({
    id: "pkg-apt-search",
    title: "搜索软件包",
    subcategory: "package",
    distroFamilies: [...deb],
    template: "apt search {pattern}",
    paramOverrides: { pattern: PKG_PATTERN },
  }),
  createBuiltinCommand({
    id: "pkg-apt-install",
    title: "安装软件包",
    subcategory: "package",
    distroFamilies: [...deb],
    template: "sudo apt install -y {package}",
  }),
  createBuiltinCommand({
    id: "pkg-apt-update",
    title: "更新软件源",
    subcategory: "package",
    distroFamilies: [...deb],
    template: "sudo apt update",
    params: [],
  }),
  createBuiltinCommand({
    id: "pkg-apt-upgrade",
    title: "升级已装软件包",
    subcategory: "package",
    distroFamilies: [...deb],
    template: "sudo apt upgrade -y",
    params: [],
  }),
  createBuiltinCommand({
    id: "pkg-apt-remove",
    title: "卸载软件包",
    subcategory: "package",
    distroFamilies: [...deb],
    template: "sudo apt remove -y {package}",
  }),
  createBuiltinCommand({
    id: "pkg-dpkg-list",
    title: "已装软件包筛选",
    subcategory: "package",
    distroFamilies: [...deb],
    template: "dpkg -l | grep {pattern}",
    paramOverrides: { pattern: PKG_PATTERN },
  }),

  // package rhel dnf
  createBuiltinCommand({
    id: "pkg-dnf-search",
    title: "搜索软件包 (dnf)",
    subcategory: "package",
    distroFamilies: [...rhel],
    template: "dnf search {pattern}",
    paramOverrides: { pattern: PKG_PATTERN },
  }),
  createBuiltinCommand({
    id: "pkg-dnf-install",
    title: "安装软件包 (dnf)",
    subcategory: "package",
    distroFamilies: [...rhel],
    template: "sudo dnf install -y {package}",
  }),
  createBuiltinCommand({
    id: "pkg-dnf-update",
    title: "检查更新 (dnf)",
    subcategory: "package",
    distroFamilies: [...rhel],
    template: "sudo dnf check-update",
    params: [],
  }),
  createBuiltinCommand({
    id: "pkg-dnf-upgrade",
    title: "升级已装软件包 (dnf)",
    subcategory: "package",
    distroFamilies: [...rhel],
    template: "sudo dnf upgrade -y",
    params: [],
  }),
  createBuiltinCommand({
    id: "pkg-dnf-remove",
    title: "卸载软件包 (dnf)",
    subcategory: "package",
    distroFamilies: [...rhel],
    template: "sudo dnf remove -y {package}",
  }),
  createBuiltinCommand({
    id: "pkg-rpm-list",
    title: "已装 RPM 筛选",
    subcategory: "package",
    distroFamilies: [...rhel],
    template: "rpm -qa | grep {pattern}",
    paramOverrides: { pattern: PKG_PATTERN },
  }),
  createBuiltinCommand({
    id: "pkg-yum-install",
    title: "安装软件包 (yum)",
    description: "适用于 CentOS 7 等旧系统",
    subcategory: "package",
    distroFamilies: [...rhel],
    template: "sudo yum install -y {package}",
  }),
  createBuiltinCommand({
    id: "pkg-yum-upgrade",
    title: "升级已装软件包 (yum)",
    description: "适用于 CentOS 7 等旧系统",
    subcategory: "package",
    distroFamilies: [...rhel],
    template: "sudo yum update -y",
    params: [],
  }),

  // package alpine
  createBuiltinCommand({
    id: "pkg-apk-search",
    title: "搜索软件包 (apk)",
    subcategory: "package",
    distroFamilies: [...alpine],
    template: "apk search {pattern}",
    paramOverrides: { pattern: PKG_PATTERN },
  }),
  createBuiltinCommand({
    id: "pkg-apk-install",
    title: "安装软件包 (apk)",
    subcategory: "package",
    distroFamilies: [...alpine],
    template: "sudo apk add {package}",
  }),
  createBuiltinCommand({
    id: "pkg-apk-update",
    title: "更新软件源 (apk)",
    subcategory: "package",
    distroFamilies: [...alpine],
    template: "sudo apk update",
    params: [],
  }),
  createBuiltinCommand({
    id: "pkg-apk-info",
    title: "软件包信息 (apk)",
    subcategory: "package",
    distroFamilies: [...alpine],
    template: "apk info {package}",
  }),

  // package suse
  createBuiltinCommand({
    id: "pkg-zypper-search",
    title: "搜索软件包 (zypper)",
    subcategory: "package",
    distroFamilies: [...suse],
    template: "zypper search {pattern}",
    paramOverrides: { pattern: PKG_PATTERN },
  }),
  createBuiltinCommand({
    id: "pkg-zypper-install",
    title: "安装软件包 (zypper)",
    subcategory: "package",
    distroFamilies: [...suse],
    template: "sudo zypper install -y {package}",
  }),
  createBuiltinCommand({
    id: "pkg-zypper-refresh",
    title: "刷新软件源 (zypper)",
    subcategory: "package",
    distroFamilies: [...suse],
    template: "sudo zypper refresh",
    params: [],
  }),

  // package arch
  createBuiltinCommand({
    id: "pkg-pacman-search",
    title: "搜索软件包 (pacman)",
    subcategory: "package",
    distroFamilies: [...arch],
    template: "pacman -Ss {pattern}",
    paramOverrides: { pattern: PKG_PATTERN },
  }),
  createBuiltinCommand({
    id: "pkg-pacman-install",
    title: "安装软件包 (pacman)",
    subcategory: "package",
    distroFamilies: [...arch],
    template: "sudo pacman -S --noconfirm {package}",
  }),
  createBuiltinCommand({
    id: "pkg-pacman-sync",
    title: "同步软件源 (pacman)",
    subcategory: "package",
    distroFamilies: [...arch],
    template: "sudo pacman -Sy",
    params: [],
  }),

  // file
  createBuiltinCommand({
    id: "file-chmod",
    title: "修改权限",
    description: "按场景选择即可，无需记忆 644、755 等数字。",
    subcategory: "file",
    distroFamilies: [...u],
    template: "chmod {mode} {path}",
    paramOverrides: {
      mode: { default: "644", inputKind: "chmod-mode", label: "文件权限" },
    },
  }),
  createBuiltinCommand({
    id: "file-chown",
    title: "修改属主",
    description: "从服务器用户列表中选择新属主；用户组可不选，表示只改属主。",
    subcategory: "file",
    distroFamilies: [...u],
    template: "sudo chown {owner}:{group} {path}",
    paramOverrides: {
      owner: { inputKind: "unix-user", label: "新属主" },
      group: { required: false, inputKind: "unix-group", label: "用户组（可选）" },
    },
  }),
  createBuiltinCommand({
    id: "file-grep",
    title: "递归搜索文件内容",
    description: "点选常见搜索类型即可，无需了解正则或 grep 语法。",
    subcategory: "file",
    distroFamilies: [...u],
    template: 'grep -rn "{pattern}" {path}',
    paramOverrides: {
      pattern: FILE_GREP_PATTERN,
      path: { placeholder: "." },
    },
  }),
  createBuiltinCommand({
    id: "file-tail",
    title: "跟踪日志文件",
    description: "Debian/Ubuntu 常用 syslog；RHEL 可改为 /var/log/messages",
    subcategory: "file",
    distroFamilies: [...u],
    template: "tail -f -n {lines} {path}",
    paramOverrides: {
      lines: { default: "100" },
      path: { placeholder: "/var/log/syslog" },
    },
  }),
  createBuiltinCommand({
    id: "file-find-name",
    title: "按文件名查找",
    subcategory: "file",
    distroFamilies: [...u],
    template:
      "find {path} -name '*{name}*' 2>/dev/null | head -n {count}",
    paramOverrides: {
      name: { ...FILE_NAME_PATTERN, placeholder: "nginx.conf" },
      count: { default: "30", label: "条数" },
    },
  }),
  createBuiltinCommand({
    id: "file-stat",
    title: "文件元信息",
    subcategory: "file",
    distroFamilies: [...u],
    template: "stat {path}",
  }),
  createBuiltinCommand({
    id: "file-tar-list",
    title: "查看压缩包内容",
    subcategory: "file",
    distroFamilies: [...u],
    template: "tar -tzf {path}",
    paramOverrides: { path: { placeholder: "/path/to/archive.tar.gz" } },
  }),

  // user
  createBuiltinCommand({
    id: "user-id",
    title: "当前用户身份",
    subcategory: "user",
    distroFamilies: [...u],
    template: "id",
    params: [],
  }),
  createBuiltinCommand({
    id: "user-who",
    title: "登录会话",
    subcategory: "user",
    distroFamilies: [...u],
    template: "w",
    params: [],
  }),
  createBuiltinCommand({
    id: "user-last",
    title: "最近登录",
    subcategory: "user",
    distroFamilies: [...u],
    template: "last -n {count}",
    paramOverrides: { count: { default: "10", label: "条数" } },
  }),
  createBuiltinCommand({
    id: "user-lastb",
    title: "失败登录记录",
    subcategory: "user",
    distroFamilies: [...u],
    template: "lastb -n {count}",
    paramOverrides: { count: { default: "10", label: "条数" } },
  }),

  // cron
  createBuiltinCommand({
    id: "cron-list",
    title: "查看当前用户 crontab",
    subcategory: "cron",
    distroFamilies: [...u],
    template: "crontab -l",
    params: [],
  }),
  createBuiltinCommand({
    id: "cron-timers",
    title: "systemd 定时器",
    subcategory: "cron",
    distroFamilies: [...u],
    template: "systemctl list-timers --all",
    params: [],
  }),
  createBuiltinCommand({
    id: "cron-system",
    title: "系统 cron 目录",
    subcategory: "cron",
    distroFamilies: [...u],
    template:
      "ls -la /etc/cron.d /etc/cron.hourly /etc/cron.daily 2>/dev/null | head -n {count}",
    paramOverrides: { count: { default: "40", label: "行数" } },
  }),

  // kernel
  createBuiltinCommand({
    id: "sys-uname",
    title: "内核与架构",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "uname -a",
    params: [],
  }),
  createBuiltinCommand({
    id: "sys-free",
    title: "内存使用",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "free -h",
    params: [],
  }),
  createBuiltinCommand({
    id: "sys-uptime",
    title: "负载与运行时间",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "uptime",
    params: [],
  }),
  createBuiltinCommand({
    id: "sys-hostnamectl",
    title: "主机信息",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "hostnamectl",
    params: [],
  }),
  createBuiltinCommand({
    id: "sys-os-release",
    title: "发行版版本",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "cat /etc/os-release",
    params: [],
  }),
  createBuiltinCommand({
    id: "sys-lscpu",
    title: "CPU 信息",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "lscpu",
    params: [],
  }),
  createBuiltinCommand({
    id: "sys-dmesg",
    title: "内核日志",
    description: "硬件/驱动相关报错",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "dmesg -T | tail -n {lines}",
    paramOverrides: { lines: { default: "50", label: "行数" } },
  }),
  createBuiltinCommand({
    id: "sys-timedatectl",
    title: "时间与时区",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "timedatectl",
    params: [],
  }),
  createBuiltinCommand({
    id: "sys-sysctl",
    title: "内核参数查询",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "sysctl {key}",
    paramOverrides: { key: { label: "参数名", placeholder: "vm.swappiness" } },
  }),
  createBuiltinCommand({
    id: "sys-env",
    title: "环境变量",
    subcategory: "kernel",
    distroFamilies: [...u],
    template: "env | sort",
    params: [],
  }),
];
